### ISSUE TITLE
WinAppDriver exception when creating a new UWP project

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4429]
### Describe the bug

System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.AddContextItemsToSolutionAndProjectPostAction'. Related template: None. ---> System.Exception: Error adding project C:\App3\App3.Tests.WinAppDriver\App3.Tests.WinAppDriver.csproj ---> System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.TryGetProperty(IVsHierarchy hierarchy, HierarchyId id, ProjectProperty property, Object& value)
   at Microsoft.VisualStudio.ProjectFlavoring.Configuration.InnerHierarchyPropertyProvider.GetProperty(HierarchyId id, ProjectProperty property, Object currentValue)
   at Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyProviderManager.TryGetProperty(IPropertyProvider provider, HierarchyId id, ProjectProperty property, Object currentValue, PropertyResult& result)
   at EnvDTE._Solution.AddFromFile(String FileName, Boolean Exclusive)
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellSolution.<AddProjectToSolutionAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellSolution.<AddProjectToSolutionAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellSolution.<AddContextItemsToSolutionAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellSolution.<>c__DisplayClass3_0.<<AddContextItemsToSolution>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellSolution.AddContextItemsToSolution(ProjectInfo projectInfo)
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.Core.Gen.GenController.ExecuteGlobalPostActions()
   at Microsoft.Templates.Core.Gen.GenController.<GenerateItemsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.Core.Gen.NewProjectGenController.<UnsafeGenerateProjectAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Services.GenerationService.<GenerateProjectAsync>d__5.MoveNext()

### To Reproduce

Add WinAppDriver test project to a new UWP project, then observe the error on project creation.

I was prompted to install a required version of .NET, which I declined and chose to not load the project. This exception might be related to that choice.

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
This doesn't repro if I select update to latest version of .NET so likely related to the project being unloaded.

**Comment by mrlacey** [comment]
Without knowing what you didn't have installed beforehand it's going to be hard to recreate this.
I also suspect that if you didn't have a UWP dependency installed then you wouldn't have been able to create a Blank UWP app.
If that's the case, then I'm not sure what we can (or should attempt to) do in this scenario.
It's already reported that you don't have a required dependency and has given you the opportunity to add it.

This reproduction is equivalent to saying "I don't have all the required dependencies installed and I'm deliberately trying to use the tool in an environment that doesn't have them."
This isn't a supported scenario and isn't something I'm inclined to spend a lot of time on.

**Comment by mikebattista** [comment]
Agreed. Assuming you have all dependencies and choose mitigations that are presented, this isn't a problem.
