### ISSUE TITLE
Pipelines intermittently failing with Could not load type 'Microsoft.Internal.VisualStudio.Shell.Interop.IVsExecutionContextTracker'

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4491]
### Describe the bug

The tests have recently started failing (I think intermittently) with the below error, possibly related to the fact that it's an internal VS binary and VS 17.2 just shipped.

      System.TypeInitializationException : The type initializer for 'Microsoft.Templates.UI.Threading.SafeThreading' threw an exception.
      ---- System.TypeLoadException : Could not load type 'Microsoft.Internal.VisualStudio.Shell.Interop.IVsExecutionContextTracker' from assembly 'Microsoft.Internal.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Stack Trace:
           at Microsoft.Templates.UI.Threading.SafeThreading.get_JoinableTaskFactory()
        D:\a\1\s\code\SharedFunctionality.UI\ViewModels\Common\SelectableGroup`1.cs(27,0): at Microsoft.Templates.UI.ViewModels.Common.SelectableGroup`1.set_Selected(T value)
        D:\a\1\s\code\SharedFunctionality.UI\ViewModels\NewProject\MainViewModel.cs(198,0): at Microsoft.Templates.UI.ViewModels.NewProject.MainViewModel.<ProcessItemAsync>d__39.MoveNext()

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
I think I have a fix for this but it will mean setting the minimum supported VS version to 17.2
I need to test a bit more before I can raise a PR - making this a priority for tomorrow.

**Comment by mikebattista** [comment]
Thanks. Setting the minimum version to 17.2 for developing Template Studio? Or for using it?

**Comment by mrlacey** [comment]
> Thanks. Setting the minimum version to 17.2 for developing Template Studio? Or for using it?

I suspect both. :/

**Comment by mrlacey** [comment]
For future reference. Old versions of VS can be obtained from https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-history#fixed-version-bootstrappers

**Comment by mikebattista** [comment]
FYI, since updating to 17.2, I get this same error when I try to use the VsEmulator to create a project:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Templates.UI.Threading.SafeThreading' threw an exception.

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Templates.UI.Threading.SafeThreading.SafeThreading() in SafeThreading.cs

Inner Exception 1:
TypeLoadException: Could not load type 'Microsoft.Internal.VisualStudio.Shell.Interop.IVsExecutionContextTracker' from assembly 'Microsoft.Internal.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Repro is launch the VsEmulator then click New WinUI C# Project.
