### ISSUE TITLE
VSIX Installer Fails to install Template Studio

### ISSUE THREAD

**Issue by operat1ve** [microsoft/TemplateStudio#4709]
### Describe the bug

8/23/2023 9:09:21 AM - Microsoft VSIX Installer
8/23/2023 9:09:21 AM - -------------------------------------------
8/23/2023 9:09:21 AM - vsixinstaller.exe version:
8/23/2023 9:09:21 AM - 17.7.2190+64154d9aa7
8/23/2023 9:09:21 AM - -------------------------------------------
8/23/2023 9:09:21 AM - Command line parameters:
8/23/2023 9:09:21 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:17.7.34009.444,/appidname:Microsoft Visual Studio Community 2022,/culture:en-US,/noep,C:\Users\user\AppData\Local\Temp\VSIXzhjujyil.vsix
8/23/2023 9:09:21 AM - -------------------------------------------
8/23/2023 9:09:21 AM - Microsoft VSIX Installer
8/23/2023 9:09:21 AM - -------------------------------------------
8/23/2023 9:09:21 AM - System.NullReferenceException: Object reference not set to an instance of an object.
   at VSIXInstaller.SetupExtensions.GetLaunchableInstances(IQuery query) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\SetupExtensions.cs:line 49
   at VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\SupportedSKUs.cs:line 236
   at VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken, String rootSuffix) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\SupportedSKUs.cs:line 229
   at VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken, String rootSuffix) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\SupportedSKUs.cs:line 170
   at VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 303
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 259
   at VSIXInstaller.App.Initialize() in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 225
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

### To Reproduce

 1. On Windows 10 with Visual Studio 2022
 2. Go To Visual Studio Marketplace and search for Template Studio, then click Download
 3. Exit VS2022 so that installation starts.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  Version 17.7.1
 - Template Studio Wizard Version: 5.4
 - Windows Build: 22H2 (OS Build 19045.3324)

**Comment by operat1ve** [comment]
https://stackoverflow.com/questions/65673822/vsix-installer-gives-error-object-reference-not-set-to-an-instance-of-an-object#:~:text=What%20solved%20the%20issue%20was%20deleting%20old%20broken,try%20again.%20Sorting%20by%20creation%20date%20might%20help.
